image: node:latest

stages:
    - development
    - staging
    - production

development:
    type: deploy
    stage: development
    script:
        - git push -f -q https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_DEVELOPMENT.git HEAD:develop
    only:
        - develop

staging:
    type: deploy
    stage: staging
    script:
        - git push -f -q https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git HEAD:staging
    only:
        - staging

production:
    type: deploy
    stage: production
    script:
        - git push -f -q https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_PRODUCTION.git HEAD:main
    only:
        - main