dateModified: 1623406775
email:
  fromEmail: sp@stefanoperfili.com
  fromName: Nextcraft
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  sidebar-admin-links:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Nextcraft
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
